DROP TABLE IF EXISTS TBL_POSTS;

CREATE TABLE TBL_POSTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  userId VARCHAR(250) NOT NULL,
  content VARCHAR(250) NOT NULL,
  emotion VARCHAR(250)
--  creationDate Date
);
